# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{geokit-cache}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcin Nowicki"]
  s.date = %q{2009-09-24}
  s.description = %q{Caching support in database for locations geocoded by andre/geokit-gem}
  s.email = %q{pr0d1r2@ragnarson.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/geokit_cache/geokit_cache_generator.rb",
     "generators/geokit_cache/templates/model.rb",
     "generators/geokit_cache/templates/model_spec.rb",
     "geokit-cache.gemspec",
     "lib/geokit-cache.rb",
     "lib/geokit/cache/active_record.rb",
     "lib/geokit/cache/model.rb",
     "spec/geokit-cache_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/Pr0d1r2/geokit-cache}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Geokit caching support}
  s.test_files = [
    "spec/geokit-cache_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<Pr0d1r2-active_record_connectionless>, [">= 0"])
      s.add_development_dependency(%q<Pr0d1r2-active_record_geocodable>, [">= 0"])
      s.add_development_dependency(%q<htmlentities>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<Pr0d1r2-active_record_connectionless>, [">= 0"])
      s.add_dependency(%q<Pr0d1r2-active_record_geocodable>, [">= 0"])
      s.add_dependency(%q<htmlentities>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<Pr0d1r2-active_record_connectionless>, [">= 0"])
    s.add_dependency(%q<Pr0d1r2-active_record_geocodable>, [">= 0"])
    s.add_dependency(%q<htmlentities>, [">= 0"])
  end
end
